### ISSUE TITLE
Lots of irrelevant things shown before an example app

### ISSUE THREAD

**Issue by blokhin** [hyoo-ru/todomvc.hyoo.ru#2]
After I browse to http://127.0.0.1:9080 I see this screen:

![screenshot-d07aaa7a](https://user-images.githubusercontent.com/177388/200335201-aa07a861-d817-42d7-b542-a08935203d05.jpg)

I should admit this is very misleading, since I expect to see the app, but instead I have to navigate through the bunch of links, twice.

Is there any way to skip these two screens and show the app immediately?

**Comment by nin-jin** [comment]
Single development server provides automatic build of any application from the MAM-ecosystem on request.

**Comment by blokhin** [comment]
@nin-jin please let me propose this minor change into the readme then

**Comment by nin-jin** [comment]
What change do you mean?
